day23/empprj/empapp/urls.py
from django.urls import path
from empapp import views


# generic class based view

urlpatterns = [
    
    path('list/',views.EmployeeListView.as_view(), name='list'),
    path('create/',views.EmployeeCreateView.as_view(), name='create'),
    path('detail/<int:pk>',views.EmployeeDetailView.as_view(), name='detail'),
    path('edit/<int:pk>',views.EmployeeUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>',views.EmployeeDeleteView.as_view(), name='delete'),
    path('showchart/<str:chartType>/', views.showchart,name='showchart'),
    path('department/<str:departmentname>/', views.show,name='employees_by_department'),
    path('department/', views.show,name='alldepartment'),
    path('search/', views.search,name='search'),
]

day23/empprj/empprj/urls.py
from django.contrib import admin
from django.urls import path,include
from empapp import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomeView.as_view(), name='home'),
    path('emp/',include('empapp.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    

day23/empprj/empapp/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Department(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField('Department Name',max_length=100)
    
    def __str__(self):
        return self.name
    
class Employee(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField('Employee Name',max_length=100)
    email = models.EmailField(max_length=100,null=True,blank=True,verbose_name=('Email Address'))
    dob = models.DateField('Birth Date',default=timezone.now,blank=True,help_text='format:yyyy-mm-dd')
    salary = models.DecimalField('Monthly Salary',max_digits = 8,decimal_places=2,blank=True,null=True)
    photo = models.FileField(upload_to = "empimage",default = "empimage/blank.png",blank=True)
    department = models.ForeignKey(Department,on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return "/"

day23/empprj/empapp/forms.py
from django import forms
from empapp.models import Employee

class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = "__all__"

day23/empprj/empapp/views.py
from django.shortcuts import render, get_object_or_404
from django.urls.base import reverse_lazy
from django.views.generic import *
from empapp.models import Employee, Department
from empapp.forms import EmployeeForm
from django.contrib import messages
from django.urls import reverse
from django.db.models import Count
from django.db.models import Q

# Create your views here.

# generic class based view

class HomeView(TemplateView):
    template_name = 'emp/home.html'
    
class EmployeeListView(ListView):
    model = Employee
    template_name = 'emp/list.html'
    # paginate_by = 10
    queryset = Employee.objects.order_by('-id')
    
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Employee List"
        return context    
    
class EmployeeCreateView(CreateView):
    model = Employee
    template_name = 'emp/empform.html'
    form_class = EmployeeForm
    
    def get_success_url(self)->str:
        messages.add_message(self.request,messages.INFO,'Employee Created Successfully')
        return reverse('list')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Employee Entry'
        context["heading" ] = 'Create New Employee'
        return context   
    
class EmployeeDetailView(DetailView):
    queryset = Employee.objects.all()
    template_name = 'emp/details.html' 
    
class EmployeeUpdateView(UpdateView):
    model = Employee
    template_name = 'emp/empform.html'
    form_class = EmployeeForm
    
    def get_success_url(self):
        messages.add_message(self.request, messages.INFO,'Employee Has Been Updated')
        return reverse('list')  
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Edit Employee'
        context["heading" ] = 'Update Employee'
        return context  
    
class EmployeeDeleteView(DeleteView):
    model = Employee
    template_name = 'emp/delete.html'
    form_class = EmployeeForm 
    # success_url = reverse_lazy('list') 
    
    
    def get_success_url(self):
        messages.add_message(self.request, messages.INFO,'Employee Has Been Deleted')
        return reverse('list') 
    

def showchart(request, chartType):
    labels = []
    data = []
    queryset = Employee.objects.values('department__name').annotate(num_employees= Count('department_id')).all()
    for emp in queryset:
        labels.append(emp['department__name'])
        data.append(emp['num_employees'])
    
    context = {'title': 'Chart', 'labels': labels, 'data': data, 'chartType': chartType}    
    return render(request, 'emp/chart.html',context) 

def show(request, departmentname = None):
    departments = None
    employees = None


    if departmentname != None:
        departments = get_object_or_404(Department,name=departmentname)
        employees = Employee.objects.filter(department=departments)
        page_employees = employees
        emp_count = employees.count()

    else:
        employees = Employee.objects.all().order_by('id')
        page_employees = employees
        emp_count = employees.count()

    context = {
        'object_list':page_employees,
        'emp_count': emp_count,
    }
    return render(request, 'emp/list.html', context)

def search(request):
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        if keyword:
            employees=Employee.objects.order_by('-name').filter(Q(name__contains=keyword)| 
                                                                Q(email__contains=keyword)|
                                                                Q(salary__contains=keyword) |
                                                                Q(dob__contains=keyword)
                                                                )
            emp_count = employees.count()

    context = {
        'object_list':employees,
        'emp_count': emp_count,
    }
    return render(request, 'emp/list.html', context)

    
    
    
    

day23/empprj/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% include 'mdbcss.html' %}
    {% block stylesheet %}
        
    {% endblock stylesheet %}
        
</head>
<body>
    <header>
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <h1>
                        <a href="">
                            <img src="{% static 'images/logo.png' %}" alt="" class="logo" width="100%">
                        </a>
                    </h1>
                </div>

            </div>
            {% include 'includes/navbar.html' %}
        </div>
    </header>
    <br><br>
    <main>
        <div class="container" style="min-height:600px;">
            
            {% block content %}
                
            {% endblock content %}
                

        </div>
        {% include 'includes/footer.html' %}
    </main>

    {% include 'mdbjs.html' %}
    
    {% block javascript %}
        
    {% endblock javascript %}

    <script>
        $(function(){
            setTimeout(function(){
                $('.alert').hide();
            },2000);
            $("#id_dob").datepicker({
                format:"yyyy-mm-dd",
                autoclose: true,
                todayHightlight: true,
                endDate:'-0d'
            });
            $("#id_photo").change(function() {
                readURL(this);
            });
            
            $("#my_modal").modal("show");

            $('#emptable').DataTable({
                "dom":'f<t>ip',
                //"dom": '<"top"f>rt<"bottom"p><"clear">', // Positions table elements
                "lengthMenu": [
                [10, 25, 50, -1],
                [10, 25, 50, "All"]
                ]

            });
        });
    
        function readURL(input) {
            var filepath = input.value;
            var allowed_extensions = /(\.jpg|\.png|\.gif)$/i;
            if (!allowed_extensions.exec(filepath)) {
                alert('Invalid file type !!!');
                input.value = '';
                return false;
            } 
            else 
            {
                if (input.files && input.files[0]) {
                    var reader = new FileReader();
                    reader.onload = function(e) {
                        $('.blah')
                            .attr('src', e.target.result).width(500);
                    };
                    reader.readAsDataURL(input.files[0]);
                }
            }
        }
            
    </script>
        
</body>
</html>

day23/empprj/templates/emp/chart.html
{% extends 'base.html' %}


{% block title %}  {{ title }}{% endblock title %}


{% block content %}
<div class="container" style="width:75%">
    <canvas id="bar-chart" width="800" height="450"></canvas>
</div>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
<script>
    $(function(){
        new Chart(document.getElementById("bar-chart"), {
            type: '{{ chartType }}',
            data: {
              labels:  {{ labels | safe}},
              datasets: [
                {
                  label: "Empoloyee/Department",
                  backgroundColor: ["#3e95cd", "#8e5ea2","#3cba9f","#e8c3b9","#c45850"],
                  data: {{ data | safe}}

                }
              ]
            },
            options: {
              legend: { display: false },
              title: {
                display: true,
                text: 'Department wise Empoloyee Report'
              }
            }
        });

    });
</script>


{% endblock content %}
    
<!-- https://tobiasahlin.com/blog/chartjs-charts-to-get-you-started/ -->

day23/empprj/templates/emp/delete.html
{% extends 'base.html' %}

{% block content %}
    


<form method="POST" enctype="multipart/form-data" >
        {% csrf_token %}
    
        <!-- Button trigger modal -->
    
    
    <!-- Modal -->
    <div class="modal fade" id="my_modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Delete Employee</h5>
          <button type="button" class="btn-close" data-mdb-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <p>Are you sure you want to delete ?<strong>{{ object.name }}</strong>
            </p>
        </div>
        <div class="modal-footer">
            <a href="{% url 'list' %}" class="btn btn-primary">Back to list</a>
          <button type="submit" class="btn btn-danger">Confirm Delete</button>
        </div>
      </div>
    </div>
    </div>
    
    </form>

<!-- JQuery -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<!-- MDB -->
<script
  type="text/javascript"
  src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.10.1/mdb.min.js"
></script>

<script>
    $(function(){
        $("#my_modal").modal("show");
    });
</script>


{% endblock content %}
      


    

day23/empprj/templates/emp/delete1.html
{% extends 'base.html' %}
    
{% block content %}
    

    

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}


    <!-- Button trigger modal -->


<!-- Modal -->
<div
class="modal fade"
id="my_modal"
tabindex="-1"
aria-labelledby="exampleModalLabel"
aria-hidden="true"
>
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title" id="exampleModalLabel">Delete Employee</h5>
      <button
        type="button"
        class="btn-close"
        data-mdb-dismiss="modal"
        aria-label="Close"
      ></button>
    </div>
    <div class="modal-body">
        <p>Are you sure  you want to delete ? <strong>
            {{ object.name }}
        </strong></p>
    </div>
    <div class="modal-footer">
        <a href="{% url 'list' %}" class="btn btn-primary">Back to list</a>

      <button type="submit" class="btn btn-danger">Confim Delete</button>
    </div>
  </div>
</div>
</div>
</form>

{% endblock content %}

day23/empprj/templates/emp/details.html
{% extends 'base.html' %}
{% load static %}

{% block content %}  



<form action="" method="POST" enctype="multipart/form-data">

    <!-- cross reference mendatory -->
    {% csrf_token %}
    
    
        

<div class="row">
    <div class="col-sm-6">
        <div class="card">
           <div class="card-header">
            <h1>Employee Details</h1>
           </div>
            <div class="card-body">
              <div class="form-group row">
                <label class="col-sm-4">
                    Employee ID
                </label>
                <div class="col-sm-4">{{ object.id }}</div>
              </div>
              <div class="form-group row">
                <label class="col-sm-4">
                    Employee Name
                </label>
                <div class="col-sm-4">{{ object.name }}</div>
              </div>
              <div class="form-group row">
                <label class="col-sm-4">
                    Email Address
                </label>
                <div class="col-sm-5">{{ object.email }}</div>
              </div>
              <div class="form-group row">
                <label class="col-sm-4">
                    Date Of Birth
                </label>
                <div class="col-sm-4">{{ object.dob|date:'Y-m-d' }}</div>
              </div>
              <hr>
                <a href="{% url 'list' %}" class="btn btn-warning mt-3">Back to list</a>
            </div>
          </div> 

    </div>
    <div class="col-sm-6">
        <div class="card">
            <div class="card-header">
             ...
            </div>
             <div class="card-body">
               <img src="{{ object.photo.url }}" alt="" class="blah" width="500px">
             </div>
           </div> 
    </div>

</div>
</form> 
    
{% endblock content %}
    

day23/empprj/templates/emp/empform.html
{% extends 'base.html' %}
{% load static %}

{% block content %}  



<form action="" method="POST" enctype="multipart/form-data">

    <!-- cross reference mendatory -->
    {% csrf_token %}
    
    
        

<div class="row">
    <div class="col-sm-6">
        <div class="card">
           <div class="card-header">
            <h1>{{ heading }}</h1>
           </div>
            <div class="card-body">
                {% load crispy_forms_tags %}
                {{ form | crispy }}
                <br>
                <button type="submit" class="btn btn-primary mt-3">Submit</button>
                <a href="{% url 'list' %}" class="btn btn-warning mt-3">Back to list</a>
            </div>
          </div> 

    </div>
    <div class="col-sm-6">
        <div class="card">
            <div class="card-header">
             ...
            </div>
             <div class="card-body">
               <img src="{{ object.photo.url }}" alt="" class="blah" width="500px">
             </div>
           </div> 
    </div>

</div>
</form> 
    
{% endblock content %}
    

day23/empprj/templates/emp/home.html
{% extends 'base.html' %}

{% block content %}

<form action="">
    <div class="jumpbotron">
        <h1 class="display-4">
            Home Page
        </h1>
        <p class="lead">Web Application Using Django</p>
        <hr class="my-4">
        <p>Python Batch 7 BITM</p>
        <a href="#" class="btn btn-primary btn-lg">Learn More</a>

    </div>
</form>
    
{% endblock content %}
    

day23/empprj/templates/emp/list.html
{% extends 'base.html' %}

{% block content %}
   <form action="" method="POST">
       {% csrf_token %}

       {% if messages %}
    
    {% for message in messages %}

    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong>{{ message }}</strong> You should check in on some of those fields below.
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
        
    {% endfor %}
    
    
        
    {% endif %}

       <a href="{% url 'create' %}" class="btn btn-primary mb-5">
            Add New Record
       </a>

       <div class="container">
           <p>Total Employee in Department : {{ emp_count }} </p>
           <table class="mdl-data-table" style="width:100%" id="emptable" data-page-length ="8">
            <thead  class="table-dark" >  
                <tr>
                   <td>Employee ID</td>
                   <td>Employee Name</td>
                   <td>Email Address</td>
                   <td>Date of Birth</td>
                   <td>Salary</td>
                   <td>Department</td>
                   <td>Photo</td>
                   <td>...</td>
               </tr>
            </thead>
            <tbody>    
               {% for emp in object_list %}
               <tr>
                <td>{{ emp.id }}</td>
                <td>{{ emp.name|title }}</td>
                <td>{{ emp.email }}</td>
                <td>{{ emp.dob|date:'Y-m-d' }}</td>
                <td>{{ emp.salary }}</td>
                <td>{{ emp.department }}</td>
                <td>
                    <img src="{{ emp.photo.url }}" alt="" width="100px">
                </td>
                <td>
                    <a href="{% url 'detail' emp.id %}"><i class="fa fa-eye fa-2x"></i></a>
                    <a href="{% url 'edit' emp.id %} "><i class="fa fa-edit fa-2x"></i></a>
                    <a href="{% url 'delete' emp.id %}"><i class="fa fa-trash fa-2x"></i></a>
                </td>

            </tr>
               {% endfor %}
            </tbody>
                   
               
           </table>

           
       </div>

   </form>
{% endblock content %}

day23/empprj/templates/includes/footer.html
<footer class="text-center font-small fade-in">
    <div class="py-3">
        &copy;copyright{% now 'Y' %} Dhaka,Bangladesh
        <a href="http://www.google.com" target="_blank">Gulshan Rahman
    </div>

</footer>

day23/empprj/templates/includes/navbar.html
<!-- Font Awesome -->
<link
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
  rel="stylesheet"
/>
<!-- Google Fonts -->
<link
  href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
  rel="stylesheet"
/>
<!-- MDB -->
<link
  href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.10.1/mdb.min.css"
  rel="stylesheet"
/>


<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'list' %}">Employee List</a>
          </li>
        <!-- Navbar dropdown -->
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            id="navbarDropdown"
            role="button"
            data-mdb-toggle="dropdown"
            aria-expanded="false"
          >
            Others
          </a>
          <!-- Dropdown menu -->
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li>
              <a class="dropdown-item" href="{% url 'showchart' 'bar' %}">Bar Chart</a>
            </li>

            <li>
              <a class="dropdown-item" href="{% url 'showchart' 'pie' %}">Pie Chart</a>
            </li>

            <li>
              <a class="dropdown-item" href="{% url 'showchart' 'line' %}">Line Chart</a>
            </li>

            <li>
              <a class="dropdown-item" href="{% url 'showchart' 'doughnut' %}">Doughnut Chart</a>
            </li>

            <li>
              <a class="dropdown-item" href="#">Another action</a>
            </li>
            <li><hr class="dropdown-divider" /></li>
            <li>
              <a class="dropdown-item" href="#">Something else here</a>
            </li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            id="navbarDropdown"
            role="button"
            data-mdb-toggle="dropdown"
            aria-expanded="false"
          >
            Departments
          </a>
          <!-- Dropdown menu -->
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li>
              <a class="dropdown-item" href="{% url 'alldepartment' %}">All Departments</a>
            </li>
            
     
            <li><hr class="dropdown-divider" /></li>
            
            {% for dept in links  %}
            <li>
              <a class="dropdown-item" href="{{ dept.get_url }} ">{{ dept.name }}</a>
            </li>
            {% endfor %}
              

          </ul>
        </li>

          <li class="nav-item">
            <a class="nav-link disabled">Disabled</a>
          </li>
        </ul>
        <form action="{% url 'search' %}" method="GET" class="d-flex">
          <input name ="keyword" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>
  

  <script
  type="text/javascript"
  src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.10.1/mdb.min.js"
></script>

day23/empprj/templates/mdbcss.html
<!-- https://mdbootstrap.com/md-bootstrap-cdn/ -->

 <!-- Font Awesome  -->
 <!-- https://cdnjs.com/libraries/font-awesome -->
<!-- <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"> -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">
<!-- Google Fonts --> 
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
<!-- Bootstrap core CSS -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">
<!-- Material Design Bootstrap --> 
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/css/mdb.min.css" rel="stylesheet">

<!-- Copy from https://datatables.net/examples/styling/material.html -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/material-components-web/4.0.0/material-components-web.min.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4-4.1.1/dt-1.10.18/datatables.min.css"/>
<!-- OPtional -->
<!-- <link href="https://cdn.datatables.net/1.10.21/css/dataTables.material.min.css" rel="stylesheet"> -->

<!-- https://cdnjs.com/libraries/bootstrap-datepicker -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/css/bootstrap-datepicker.min.css">

day23/empprj/templates/mdbjs.html
<!-- https://mdbootstrap.com/md-bootstrap-cdn/ -->

<!-- JQuery -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.min.js"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/js/mdb.min.js"></script>

<!-- Data Table -->


<script type="text/javascript" src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.11.3/js/dataTables.bootstrap5.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.21/js/dataTables.material.min.js"></script>

<!-- Date Picker -->
<!-- https://cdnjs.com/libraries/bootstrap-datepicker -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/js/bootstrap-datepicker.min.js"></script>